MODEL:
  TYPE: Generalized_SPN
  CONV_BODY: ResNet.ResNet50_conv4_body
  FASTER_RCNN: False
  NUM_CLASSES: 19
RESNETS:
    IMAGENET_PRETRAINED_WEIGHTS: 'lib/datasets/pretrain_model/resnet50-19c8e357.pth'
SEM:
    SEM_ON: True
    UNION: False
    FC_DIM: 2048
    DIM: 512
    INPUT_SIZE: [128, 128]
    TRAINSET: 'train'
    DEEP_SUB_SCALE: [1.0]
    DOWNSAMPLE: [0]
    OUTPUT_PREFIX: 'semseg_label'
SPN:
    SPN_ON: True
    DIM: 32
    SAVE_FILE: ""
    SPN_ITERS: 1
    DIM: 32
DISP:
    DISP_ON: False
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.005
  TYPE: 'poly'
  LR_POLICY: 'Poly'
  BASE_LR: 0.0001
  POLY_POWER: 0.5
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: False
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  #SCALES: (1024,1536,2048,2560,3072,3584,4096)
  SCALES: (2048,)
  MAX_SIZE: 1440
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  IMS_PER_BATCH: 6
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: ./output/cityscapes/spn_origin
